# Generated by Django 4.2.30 on 2026-04-17 00:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(null=True)),
                ('matric_card', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('id_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('whatsapp', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_delivery', models.BooleanField(default=True)),
                ('delivery_locations', models.JSONField(default=list)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0)),
                ('rating_average', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['verification_status', 'is_active'], name='stores_stor_verific_638192_idx'), models.Index(fields=['slug'], name='stores_stor_slug_e2ab60_idx')],
            },
        ),
    ]
