# Generated by Django 4.2.30 on 2026-04-17 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Seller Acceptance'), ('accepted', 'Accepted by Seller'), ('preparing', 'Preparing Order'), ('in_transit', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('rejected', 'Rejected by Seller'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('delivery_location', models.CharField(max_length=200)),
                ('delivery_method', models.CharField(max_length=100)),
                ('delivery_notes', models.TextField(blank=True)),
                ('estimated_delivery', models.DateTimeField(null=True)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_whatsapp', models.CharField(blank=True, max_length=15)),
                ('seller_response_deadline', models.DateTimeField()),
                ('seller_accepted_at', models.DateTimeField(null=True)),
                ('seller_rejected_at', models.DateTimeField(null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('auto_rejected', models.BooleanField(default=False)),
                ('seller_marked_delivered_at', models.DateTimeField(null=True)),
                ('buyer_confirmed_delivery_at', models.DateTimeField(null=True)),
                ('auto_completed', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True)),
                ('dispute_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(default='pay_on_delivery', max_length=50)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='orders_orde_buyer_i_67c51b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'seller_response_deadline'], name='orders_orde_status_b18cfa_idx'),
        ),
    ]
